name: linux

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cvmfs_base: ['sft.cern.ch/lcg/views']
        ENVIRONMENT: ['LCG_99/x86_64-centos7-gcc8-opt',
                      'dev3/latest/x86_64-centos7-gcc10-opt',
                      'dev4/latest/x86_64-centos7-clang11-opt']
        include:
        - cvmfs_base: 'sw.hsf.org'
          ENVIRONMENT: 'key4hep'
        - cvmfs_base: 'sw-nightlies.hsf.org'
          ENVIRONMENT: 'key4hep'
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@v3
      with:
        container: centos7
        view-path: "/cvmfs/${{ matrix.cvmfs_base }}/${{ matrix.ENVIRONMENT }}"
        run: |
          mkdir build install
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " \
            -G Ninja ..
          ninja -k0
          ctest --output-on-failure
          ninja install
